# lang/en.ini
[main]
app_title = Demon System
settings_title = Settings
language = Language
language_desc = Select application language
theme = Theme
theme_desc = Light or dark mode
other = Other
other_desc = Additional settings
about_us = About Us
about_us_desc = App information